services:
  homeassistant-korea-2025:
    container_name: homeassistant-korea-2025
    image: "homeassistant/home-assistant:2025.8"
    volumes:
      - ./configuration.yaml:/config/configuration.yaml
      - ../custom_components/korea_incubator:/config/custom_components/korea_incubator
    restart: unless-stopped
    privileged: true
    environment:
      - TZ=Asia/Seoul
    ports:
      - "8123:8123"
      - "6789:6789"
    networks:
      - podman-default

networks:
  podman-default:
    external: true
